services:
  hooks-localhost:
    build:
      context: .
      dockerfile: 'Dockerfile'
      args:
        ORIGIN: ${ORIGIN}
    image: ghcr.io/moritzloewenstein/hooks-localhost:latest
    volumes:
      - hooks_localhost_data:/app/data

volumes:
  hooks_localhost_data:
